version: '3.8'
services:
  vulnbuster:
    build: .
    container_name: vulnbuster
    volumes:
      - ./reports:/app/reports
    depends_on:
      - dashboard
    command: ["python", "main.py"]

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: dashboard
    environment:
      - DASHBOARD_TOKEN_FILE=/app/dashboard.env
    ports:
      - "8000:8000"
    volumes:
      - ./reports:/app/reports
      - ./dashboard.env:/app/dashboard.env
    command: ["python", "-m", "webui.dashboard"]

  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - vulnbuster
      - dashboard 